version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "In pre_build stage"  
      - pip install -r requirements.txt
      - echo "after requirement step"
  build: 
    commands:
      - echo "In build stage"
